services:
  chat_server_postgresql:
    image: postgres-pgtextsearch
    restart: always
    environment:
      POSTGRES_USER: chat_server
      POSTGRES_PASSWORD: eWFwdDGJMpDm2NYVJuxjpkcDK50NAgu6EAv
      POSTGRES_DB: chat_server
    ports:
      - "5532:5432"
    volumes:
      - ./pgdata/:/var/lib/postgresql/

