services:
  chat_server_postgresql:
    image: postgres-pgtextsearch
    restart: always
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${DOCKER_POSTGRESQL_DATABASE}
    ports:
      - "${DOCKER_POSTGRESQL_PORT}:5432"
    volumes:
      - ./pgdata/:/var/lib/postgresql/

